/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.g2m2e1.redflix45.views;

import co.g2m2e1.redflix45.Context;
import co.g2m2e1.redflix45.models.Shows;
import co.g2m2e1.redflix45.repositories.ShowsRepository;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ESLUNAP
 */
public class JPanelSerieR extends javax.swing.JPanel {

    ShowsRepository showRepository;
    /**
     * Creates new form JPanelSerie
     */
    public JPanelSerieR() {
        initComponents();
        showRepository = Context.getBean(ShowsRepository.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextFieldTituloSerie = new javax.swing.JTextField();
        jTextFieldNoCaps = new javax.swing.JTextField();
        jTextFieldNoTemp = new javax.swing.JTextField();
        jButtonGuardarS = new javax.swing.JButton();
        jButtonLimpiarCampos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldTituloSerie.setBorder(javax.swing.BorderFactory.createTitledBorder("Título serie"));
        add(jTextFieldTituloSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 255, -1));

        jTextFieldNoCaps.setBorder(javax.swing.BorderFactory.createTitledBorder("No. Capítulos"));
        add(jTextFieldNoCaps, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 79, 93, -1));

        jTextFieldNoTemp.setBorder(javax.swing.BorderFactory.createTitledBorder("No. Temporadas"));
        add(jTextFieldNoTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 79, 127, -1));

        jButtonGuardarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscar.png"))); // NOI18N
        jButtonGuardarS.setText("Consultar");
        jButtonGuardarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarSActionPerformed(evt);
            }
        });
        add(jButtonGuardarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jButtonLimpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escoba.jpeg"))); // NOI18N
        jButtonLimpiarCampos.setText("Limpiar Campos");
        jButtonLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCamposActionPerformed(evt);
            }
        });
        add(jButtonLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabel1.setText("Consulta por Título Serie");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarSActionPerformed
        // TODO add your handling code here:
        String show = jTextFieldTituloSerie.getText();
        try {
            List<Shows> serie = showRepository.findByShowTitle(show);
            if (show.isEmpty()) {
                System.out.println("Por favor digite el nombre de la serie");
                JOptionPane.showMessageDialog(null, "Por favor digite el nombre de la serie", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (!serie.isEmpty()) {
                for (Shows s : serie) {
                    System.out.println("Serie disponible: " + s.getShowTitle() + " consta de " + s.getShowEpisodes() + " episodios en " + s.getShowSeasons() + " temporadas");
                    jTextFieldNoCaps.setText(s.getShowEpisodes());
                    jTextFieldNoTemp.setText(s.getShowSeasons());
                }
            } else {
                System.out.println("La serie que busca no fue encontrada");
                JOptionPane.showMessageDialog(null, "La serie " + show + " no fue encontrada", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println("Error al consultar la serie");
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al consultar la serie", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarSActionPerformed

    private void jButtonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCamposActionPerformed
        // TODO add your handling code here:
        JTextField caja;
        for (int i = 0; i< this.getComponentCount();i++){
            if(this.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                caja = (JTextField)this.getComponent(i);
                caja.setText("");            
            }        
        }
        jTextFieldTituloSerie.requestFocus();
    }//GEN-LAST:event_jButtonLimpiarCamposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardarS;
    private javax.swing.JButton jButtonLimpiarCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNoCaps;
    private javax.swing.JTextField jTextFieldNoTemp;
    private javax.swing.JTextField jTextFieldTituloSerie;
    // End of variables declaration//GEN-END:variables
}
