/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.g2m2e1.redflix45.views;

import co.g2m2e1.redflix45.Context;
import co.g2m2e1.redflix45.models.Movies;
import co.g2m2e1.redflix45.repositories.MoviesRepository;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author ESLUNAP
 */
public class JPanelPeliculaD extends javax.swing.JPanel {

    MoviesRepository movieRepository;
    DefaultListModel listModel = new DefaultListModel();
    SimpleAttributeSet attribs = new SimpleAttributeSet();
        
    /**
     * Creates new form JPanelPelicula
     */
    public JPanelPeliculaD() {
        initComponents();
        movieRepository = Context.getBean(MoviesRepository.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPelicula = new javax.swing.JTextField();
        jButtonEliminarP = new javax.swing.JButton();
        jButtonLimpiarCampos = new javax.swing.JButton();
        jLabelInfoTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPelicula.setBorder(javax.swing.BorderFactory.createTitledBorder("Título película"));
        jTextFieldPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPeliculaActionPerformed(evt);
            }
        });
        add(jTextFieldPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 203, -1));

        jButtonEliminarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basura.png"))); // NOI18N
        jButtonEliminarP.setText("Eliminar");
        jButtonEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPActionPerformed(evt);
            }
        });
        add(jButtonEliminarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jButtonLimpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escoba.jpeg"))); // NOI18N
        jButtonLimpiarCampos.setText("Limpiar Campos");
        jButtonLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCamposActionPerformed(evt);
            }
        });
        add(jButtonLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabelInfoTitulo.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabelInfoTitulo.setText("Ingrese título");
        add(jLabelInfoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 129, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCamposActionPerformed
        // TODO add your handling code here:
        jTextFieldPelicula.setText("");
    }//GEN-LAST:event_jButtonLimpiarCamposActionPerformed

    private void jButtonEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPActionPerformed
        // TODO add your handling code here

        
            String idMovie = jTextFieldPelicula.getText();
            Optional<Movies> opt = movieRepository.findById(jTextFieldPelicula.getText());
            if (!idMovie.isEmpty()) {
                try {
                    if (opt.isPresent()) {
                        movieRepository.deleteById(idMovie);
                        JOptionPane.showMessageDialog(null, "Se eliminó correctamente la pelicula "+idMovie, "", JOptionPane.WARNING_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "No se encontró la pelicula con nombre "+idMovie, "", JOptionPane.WARNING_MESSAGE);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error al consultar película", "Error", JOptionPane.WARNING_MESSAGE);

                }
            } else {
                JOptionPane.showMessageDialog(null, "No ha ingresado el título de película", "", JOptionPane.WARNING_MESSAGE);
            }

            

    }//GEN-LAST:event_jButtonEliminarPActionPerformed
    
    private void jTextFieldPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPeliculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarP;
    private javax.swing.JButton jButtonLimpiarCampos;
    private javax.swing.JLabel jLabelInfoTitulo;
    private javax.swing.JTextField jTextFieldPelicula;
    // End of variables declaration//GEN-END:variables
}
