/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.g2m2e1.redflix45.views;

import co.g2m2e1.redflix45.Context;
import co.g2m2e1.redflix45.models.Movies;
import co.g2m2e1.redflix45.repositories.MoviesRepository;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author ESLUNAP
 */
public class JPanelPeliculaD extends javax.swing.JPanel {

    MoviesRepository movieRepository;
    DefaultListModel listModel = new DefaultListModel();
    SimpleAttributeSet attribs = new SimpleAttributeSet();
        
    /**
     * Creates new form JPanelPelicula
     */
    public JPanelPeliculaD() {
        initComponents();
        movieRepository = Context.getBean(MoviesRepository.class);
        //jLabelInfoTitulo.setVisible(false);
//        jLabelInfoDirector.setVisible(false);
//        jTextFieldNombreDir.setEnabled(false);
//        jrbTitulo.setSelected(true);
//        jtpResumen.setEnabled(false);
//        jtfAnno.setEnabled(false);
//        StyleConstants.setAlignment(attribs , StyleConstants.ALIGN_JUSTIFIED);
//        jtpResumen.setParagraphAttributes(attribs,true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipoConsulta = new javax.swing.ButtonGroup();
        jTextFieldPelicula = new javax.swing.JTextField();
        jButtonEliminarP = new javax.swing.JButton();
        jButtonLimpiarCampos = new javax.swing.JButton();
        jLabelInfoTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldPelicula.setBorder(javax.swing.BorderFactory.createTitledBorder("Título película"));
        jTextFieldPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPeliculaActionPerformed(evt);
            }
        });

        jButtonEliminarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basura.png"))); // NOI18N
        jButtonEliminarP.setText("Eliminar");
        jButtonEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPActionPerformed(evt);
            }
        });

        jButtonLimpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escoba.jpeg"))); // NOI18N
        jButtonLimpiarCampos.setText("Limpiar Campos");
        jButtonLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCamposActionPerformed(evt);
            }
        });

        jLabelInfoTitulo.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabelInfoTitulo.setText("Ingrese título");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButtonEliminarP)
                        .addGap(60, 60, 60)
                        .addComponent(jButtonLimpiarCampos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jTextFieldPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabelInfoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabelInfoTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarP)
                    .addComponent(jButtonLimpiarCampos))
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCamposActionPerformed
        // TODO add your handling code here:
//        btnGroupTipoConsulta.clearSelection();
//        JTextField caja;
//        for (int i = 0; i< this.getComponentCount();i++){
//            if(this.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
//                caja = (JTextField)this.getComponent(i);
//                caja.setText("");            
//            }        
//        }
//        jtpResumen.setText("");
//        listModel.clear();
//        jListPeliculas.setModel(listModel);
//        jrbTitulo.setSelected(true);
    }//GEN-LAST:event_jButtonLimpiarCamposActionPerformed

    private void jButtonEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPActionPerformed
        // TODO add your handling code here

        
            String idMovie = jTextFieldPelicula.getText();
            Optional<Movies> opt = movieRepository.findById(jTextFieldPelicula.getText());
            if (!idMovie.isEmpty()) {
                try {
                    if (opt.isPresent()) {
                        movieRepository.deleteById(idMovie);
                        JOptionPane.showMessageDialog(null, "Se elimino correctamente la pelicula "+idMovie, "", JOptionPane.WARNING_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "No se encontro la pelicula con nombre "+idMovie, "", JOptionPane.WARNING_MESSAGE);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error al consultar película", "Error", JOptionPane.WARNING_MESSAGE);

                }
            } else {
                JOptionPane.showMessageDialog(null, "No ha el titulo de pelicula", "", JOptionPane.WARNING_MESSAGE);
            }

            

    }//GEN-LAST:event_jButtonEliminarPActionPerformed
    
    private void jTextFieldPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPeliculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupTipoConsulta;
    private javax.swing.JButton jButtonEliminarP;
    private javax.swing.JButton jButtonLimpiarCampos;
    private javax.swing.JLabel jLabelInfoTitulo;
    private javax.swing.JTextField jTextFieldPelicula;
    // End of variables declaration//GEN-END:variables
}
