/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.g2m2e1.redflix45.views;

import co.g2m2e1.redflix45.Context;
import co.g2m2e1.redflix45.models.Users;
import co.g2m2e1.redflix45.repositories.UsersRepository;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ESLUNAP
 */
public class JPanelUsuarioD extends javax.swing.JPanel {

     UsersRepository userRepository;
    /**
     * Creates new form JPanelUsuario
     */
    public JPanelUsuarioD() {
        initComponents();
        userRepository = Context.getBean(UsersRepository.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldAlias = new javax.swing.JTextField();
        jButtonBorrarU = new javax.swing.JButton();
        jButtonLimpiarCampos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldAlias.setBorder(javax.swing.BorderFactory.createTitledBorder("Alias"));
        jTextFieldAlias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAliasActionPerformed(evt);
            }
        });
        add(jTextFieldAlias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 53, 291, -1));

        jButtonBorrarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basura.png"))); // NOI18N
        jButtonBorrarU.setText("Borrar");
        jButtonBorrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUActionPerformed(evt);
            }
        });
        add(jButtonBorrarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jButtonLimpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escoba.jpeg"))); // NOI18N
        jButtonLimpiarCampos.setText("Limpiar Campos");
        jButtonLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCamposActionPerformed(evt);
            }
        });
        add(jButtonLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabel1.setText("Eliminar por alias");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 21, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBorrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUActionPerformed
        // TODO add your handling code here:
        try{
            String alias = jTextFieldAlias.getText();
            
            Optional <Users> optional =  userRepository.findById(jTextFieldAlias.getText());
            if (alias.isEmpty()){
                System.out.println("No ha digitado un alias");
                JOptionPane.showMessageDialog(null,"No ha digitado un alias","Warning",JOptionPane.WARNING_MESSAGE);
            }else if(optional.isPresent()){
                userRepository.deleteById(alias);
                jTextFieldAlias.requestFocus();
                System.out.println("Se elimino exitosamente el usuario: "+ optional.get().getUserUsername());
                JOptionPane.showMessageDialog(null, "Se elimino exitosamente el usuario: "+ optional.get().getUserUsername(),"Mensaje",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,"No se encontro un alias","Warning",JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){
            System.out.println("Error al eliminar usuario");
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error al eliminar usuario","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBorrarUActionPerformed

    private void jButtonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCamposActionPerformed
        // TODO add your handling code here:
        JTextField caja;
        for (int i = 0; i< this.getComponentCount();i++){
            if(this.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                caja = (JTextField)this.getComponent(i);
                caja.setText("");            
            }        
        }
        jTextFieldAlias.requestFocus();
    }//GEN-LAST:event_jButtonLimpiarCamposActionPerformed

    private void jTextFieldAliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAliasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAliasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarU;
    private javax.swing.JButton jButtonLimpiarCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldAlias;
    // End of variables declaration//GEN-END:variables
}
