/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.g2m2e1.redflix45.views;

import co.g2m2e1.redflix45.Context;
import co.g2m2e1.redflix45.models.Shows;
import co.g2m2e1.redflix45.repositories.ShowsRepository;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ESLUNAP
 */
public class JPanelSerieD extends javax.swing.JPanel {

    ShowsRepository showRepository;
    /**
     * Creates new form JPanelSerie
     */
    public JPanelSerieD() {
        initComponents();
        showRepository = Context.getBean(ShowsRepository.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldTituloSerie = new javax.swing.JTextField();
        jButtonGuardarS = new javax.swing.JButton();
        jButtonLimpiarCampos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldTituloSerie.setBorder(javax.swing.BorderFactory.createTitledBorder("Título serie"));

        jButtonGuardarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basura.png"))); // NOI18N
        jButtonGuardarS.setText("Eliminar");
        jButtonGuardarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarSActionPerformed(evt);
            }
        });

        jButtonLimpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escoba.jpeg"))); // NOI18N
        jButtonLimpiarCampos.setText("Limpiar Campos");
        jButtonLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCamposActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabel1.setText("Eliminar por Título Serie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTituloSerie)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonGuardarS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jButtonLimpiarCampos)))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTituloSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarS)
                    .addComponent(jButtonLimpiarCampos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarSActionPerformed
        // TODO add your handling code here:
        String idSerie = jTextFieldTituloSerie.getText();
        Optional<Shows> opt = showRepository.findById(jTextFieldTituloSerie.getText());
        if (!idSerie.isEmpty()) {
            try {
                if (opt.isPresent()) {
                    showRepository.deleteById(idSerie);
                    JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente la serie " + opt.get().getShowTitle(), "", JOptionPane.WARNING_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(null, "No se ha encontrado la serie con nombre " + idSerie, "", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                System.out.println("Error al eliminar la serie");
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al eliminar la serie", "Warning", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "No ha digitado un titulo de serie", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonGuardarSActionPerformed

    private void jButtonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCamposActionPerformed
        // TODO add your handling code here:
        JTextField caja;
        for (int i = 0; i< this.getComponentCount();i++){
            if(this.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                caja = (JTextField)this.getComponent(i);
                caja.setText("");            
            }        
        }
        jTextFieldTituloSerie.requestFocus();
    }//GEN-LAST:event_jButtonLimpiarCamposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardarS;
    private javax.swing.JButton jButtonLimpiarCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldTituloSerie;
    // End of variables declaration//GEN-END:variables
}
